---
title: "p8105_hw5_bac2214"
author: "Brianna Carnagie"
date: "2023-11-12"
output: github_document
---

### Question 1

```{r setup, include=FALSE}

library(tidyverse)
library(dplyr)
library(purrr)
library(broom)

homicide_df = read_csv("data/homicide-data.csv") |> 
  mutate(
    city_state = paste(city, state, sep = ",") |> 
      s
  )

homicides_by_city = read_csv("data/homicide-data.csv") |> 
  mutate(
    city_state = paste(city, state, sep = ",")) |> 
  group_by(city_state) |> 
  summarize(total_homicides = n(),
            unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest")))

baltimore_data = homicides_by_city |> 
  filter(city_state == "Baltimore,MD") 
  
prop_test_result = 
  prop.test(x = baltimore_data$unsolved_homicides,
            n = baltimore_data$total_homicides) |> 
  broom::tidy() |> 
  mutate(
    est_prop = estimate[1],
    conf_int = paste(conf.low, conf.high, sep = ",")) |> 
  select(est_prop,conf_int)
``` 

I am now repeating the steps for each city and state value in the homicides_by_city dataframe.
```{r}

df_to_list <- split(homicides_by_city, seq(nrow(homicides_by_city)))

prop_and_ci = function(data) 
  {
  result = prop.test(x = data$unsolved_homicides, n = data$total_homicides)
  tidy_result = tidy(result)
  estimated_proportion = tidy_result$estimate[1]
  confidence_interval = paste(tidy_result$conf.low, tidy_result$conf.high, sep = ",")
  return(data.frame(estimated_proportion, confidence_interval))
}

output <- map(df_to_list, prop_and_ci)

print(output)

```



The raw data contains details about the victim of a homicide including their name, race, age, and sex. There are also details regarding the location down to the latitude and longitude as well as the disposition of the person who committed the homicide.

